### PR TITLE
ICU-20319 archive icu4j-applets

### PR DESCRIPTION
**Pull request by srl295**
ARchive of icu4j applets

### CODE REVIEW

**Comment by srl295** [comment]
archival purposes…

**Comment by sffc** [comment]
Thanks; how should I review this PR?

**Comment by srl295** [comment]
> Thanks; how should I review this PR?

as it says in the diff, this is an archive of a zipfile that was on the old site … https://github.com/unicode-org/icu-demos/pull/5/files#diff-82113023f0e67349043e02e83a06fee9R4

you can review it as to whether it should be included. I don't know where the source to these applets are.

**Comment by sffc** [comment]
I'll defer to Markus on this as I don't know the history of these applets either.

**Pull request merged**
